tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'neovim/neovim'
brew 'bash'
brew 'colordiff'
brew 'coreutils'
brew 'ctags'
brew 'curl'
cask 'docker'
brew 'docker-completion'
brew 'openssl'
brew 'git'
cask 'google-cloud-sdk'
brew 'figlet'
brew 'findutils', args: ['with-default-names']
brew 'go'
brew 'gnu-sed', args: ['with-default-names']
brew 'gnu-tar'
brew 'gnupg2'
brew 'htop-osx'
brew 'jq'
brew 'kubernetes-cli'
brew 'kubernetes-helm'
brew 'nmap'
brew 'neovim'
brew 'python3'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'vim', args: ['with-override-system-vi']
brew 'wget'
brew 'youtube-dl'
brew 'z'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-history-substring-search'
brew 'zsh-lovers'
brew 'zsh-syntax-highlighting'
brew 'homebrew/dupes/diffutils'
brew 'homebrew/dupes/grep', args: ['with-default-names']
brew 'homebrew/dupes/less'
brew 'homebrew/dupes/make'
brew 'homebrew/dupes/openssh'
brew 'homebrew/dupes/rsync'
