# start with window 1 and pane 1 (instead of 0)
set -g base-index 1
set -g pane-base-index 1

set -g renumber-windows on

set -g default-terminal "tmux-256color"
set -as terminal-features ",foot:RGB"

set -g display-time 5000
set -g history-limit 50000

set -g mouse on

# Keybinds: Vim in copy mode, Emacs in comand prompt (prefix + :)
set -g mode-keys vi
set -g status-keys emacs

set -s escape-time 10  # ~5-100 ref: https://superuser.com/a/252717/65504

# Clipboard (Wayland)

# Use tmux's native buffer system fallback
set -g set-clipboard on

# Copy text from tmux copy-mode directly into the system clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

# Double-click mouse to select a word and copy it to system clipboard
bind-key -T copy-mode-vi DoubleClick1Pane \
    select-pane \; \
    send-keys -X select-word \; \
    run-shell -d 0.3 \; \
    send-keys -X copy-pipe-and-cancel "wl-copy"

# Triple-click mouse to select a line and copy it to system clipboard
bind-key -T copy-mode-vi TripleClick1Pane \
    select-pane \; \
    send-keys -X select-line \; \
    run-shell -d 0.3 \; \
    send-keys -X copy-pipe-and-cancel "wl-copy"

# horizontal split
unbind %
bind | split-window -h -c '#{pane_current_path}'

# vertical split
unbind '"'
bind - split-window -v -c '#{pane_current_path}'

# Create new window
bind c new-window -c '#{pane_current_path}'
bind C command-prompt -p "new window:" "new-window -n '%%'"

# vim-like pane movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# use C-h and C-l to cycle thru panes
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

# reload tmux.conf using PREFIX r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# messaging
set -g message-style fg=black,bg=yellow,bold
set -g message-command-style fg=blue,bg=black

# silence alerts
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g bell-action none

# modes
set -g clock-mode-style 24
set -g clock-mode-colour colour135
set -g mode-style fg=colour196,bg=colour238,bold

# panes
set -g pane-border-style bg=colour235,fg=colour238
set -g pane-active-border-style bg=colour236,fg=colour51

# statusbar
set -g status on
set -g status-interval 5
set -g status-justify left
set -g status-position bottom
set -g status-style bg=colour234,fg=colour137,dim
set -g status-left-length 20
set -g status-right-length 50
set -g status-left ''
set -g status-right '#[fg=colour233,bg=colour241,bold] %d/%m #[fg=colour233,bg=colour245,bold] %H:%M '

set -g window-status-style fg=colour138,bg=colour235,none
set -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

set -g window-status-current-style fg=colour81,bg=colour238,bold
set -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '

set -g window-status-bell-style fg=colour255,bg=colour1,bold
