#!/bin/bash
set -e
PATH="/usr/local/bin:$PATH"
trap 'rm -f "$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$$.tags" --exclude=node_modules --languages=-javascript,sql
mv "$$.tags" "tags"
