hash -d dot=~/github/dotfiles
hash -d pkgs="$HOME/Library/Application Support/Sublime Text 3/Packages/User"

# load groovy version manager
# [[ -d ~/.gvm ]] && . ~/.gvm/bin/gvm-init.sh

. ~/.zsh/func/_grails
