# Add here your $PATH vars

# Ruby config -- add rbenv and ruby-build to $PATH
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"

# required by rbenv
eval "$(rbenv init -)"

# alternatively, use
#if which rbenv > /dev/null; then eval "$(rbenv init - --no-rehash)"; fi

# use `less` as the default pager
export LESS='--ignore-case --raw-control-chars'
export PAGER='less'

# Set your default EDITOR tool (replace with nano, vim, Emacs etc.)
export EDITOR='subl -w'

# Colored `less` output
export LESS_TERMCAP_mb=$'\E[01;31m'         # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'    # begin bold
export LESS_TERMCAP_me=$'\E[0m'             # end mode
export LESS_TERMCAP_se=$'\E[0m'             # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'      # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'             # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m'   # begin underline

# Go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# Android PATH
#export PATH=$PATH:$HOME/android-studio/sdk/tools
#export PATH=$PATH:$HOME/android-studio/sdk/platform-tools

# EOF
