# Using '-z' option for running in native mode.
autoload -Uz promptinit compinit zcalc zmv
compinit      # use modern completion system
promptinit    # pimp my prompt
prompt adam1

# Config options
setopt extendedhistory      # save timestamp and duration
setopt histignorealldups    # ignore duplicates
setopt histfindnodups       # do not display duplicates of a line previously found
setopt histignorespace      # ignore lines which start with space
setopt histreduceblanks     # prevent extra blanks on each line from being saved
setopt incappendhistory     # incremental append, don't wait until shell exit
setopt sharehistory         # share history between zsh processes
setopt autocd               # cd just by typing the name of a directory
setopt autopushd            # flip between places in a cinch
# setopt noclobber           # avoid overwriting files. Use ! to confirm
setopt interactivecomments  # allow inline comments
setopt extended_glob        # enable extended globbing
setopt globdots             # ignore preceeding dots. '.foo' == foo
setopt complete_in_word     # complete from the cursor onwards
setopt always_to_end        # move the cursor to the end of the word after completion
setopt prompt_subst         # command substitution, parameter and arithmetic expansion
setopt hist_verify          # make a newline show the change before executing it

# unsetopt menu_complete
setopt auto_menu

# Keep 10,000 lines of history within the shell and save it to ~/.zsh_history
# Also, ignore entries with leading spaces:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# beep when no results are available
setopt beep nomatch

# Show elapsed time if a command takes longer than 10s
REPORTTIME=10

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle ':completion:*' use-cache true
# remove the trailing slash when using a directory as argument
zstyle ':completion:*' squeeze-slashes true


zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
# zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# OS X config @see:
#+ https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/ps.1.html
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,state,cputime,ucomm'

# Set your default EDITOR tool
# export EDITOR='nano'
export EDITOR='subl -w'


# Key binds
# use emacs keybindings even if EDITOR is set to vi
bindkey -e
# this will bind CTRL + back/forward arrows navigation
# bindkey ";5D" backward-word
# bindkey ";5C" forward-word

# OS X-specific config
bindkey '[C' forward-word
bindkey '[D' backward-word

# Skip to start/end of line with cmd-arrow
# bindkey '\e^[[E' beginning-of-line
# bindkey '\e^[[F' end-of-line

# Alias definitions.
# You may want to put all your additions into a separate file like
# '~/.zsh_aliases' instead of adding them here directly.

if [ -f ~/.zsh_aliases ]; then
    . ~/.zsh_aliases
fi

# Environment vars definition.
if [ -f ~/.env ]; then
    . ~/.env
fi


# EOF
